### ISSUE TITLE
Update function is not working.

### ISSUE THREAD

**Issue by timemake** [p32929/EasiestSqlLibrary#2]
All functions are working well except update function.

I added one record. 

easiestDB.addDataInTable(0,
                new Datum(1, "FirstName"),
                new Datum(2, "LastName")
        );

and tried to update with this code.

                easiestDB.updateData(0, 1,
                        new Datum(1, "aaa"),
                        new Datum(2, "bbb"));

I got this error code below.
==========================
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.String)' on a null object reference
        at org.richit.easiestsqllib.EasiestDB.updateData(EasiestDB.java:74)

**Comment by p32929** [comment]
Thanks for writing the issue

Yep, it was a bug in the library. Just updated to `1.0.0.2`
use `implementation 'com.github.p32929:EasiestSqlLibrary:1.0.0.2'` to update or check the docs for more info.
Hope, everything works now

**Comment by timemake** [comment]
Thanks for the quick response.

It works fine now.
