### ISSUE TITLE
Cleaned database when contacting the second table

### ISSUE THREAD

**Issue by UrbanSide** [p32929/EasiestSqlLibrary#3]
```
 fun EasyDB(): EasiestDB {
            return EasiestDB.init(instance)
                    .addTableColumns("Objects",
                            Column("wmid", "integer", "unique"),
                            Column("title", "text"),
                            Column("descr", "text"),
                            Column("lat", "text"),
                            Column("lng", "text"),
                    ).addTableColumns("Chat",
                            Column("uid", "text"),
                            Column("name", "text"),
                            Column("text", "text"),
                            Column("time", "text"),
                            Column("msgid", "integer", "unique")
                    )
                    .doneAddingTables()
        }
```
So I create two tables, the first fill when the user is first and do not touch anymore. Chat fill when checking new messages. And once, he cleans me the first table.
```
App.Companion.EasyDB().addDataInTable(1,
                                    new Datum("uid", uid),
                                    new Datum("name", name),
                                    new Datum("text", text),
                                    new Datum("time", time),
                                    new Datum("msgid", msgid));
```
This is a chat filling method.

**Comment by UrbanSide** [comment]
**My log in verbose**
`2021-10-11 14:04:21.760 4233-4249/com.a100rad W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.a100rad/databases/DEMO_DATABASE.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
`

**Comment by p32929** [comment]
If its okay with you, can you message me in WhatsApp or Facebook? 
You can find all my contact infos here: https://p32929.github.io/

**Comment by UrbanSide** [comment]
Honestly not very comfortable, I'm in the place where the Internet works badly.

**Comment by p32929** [comment]
In that case, is it okay for you to send me the source code via dropbox or google drive?
Not sure what went wrong, but it seems the code is okay so far. I think, something else is conflicting with it...
