### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ghaizar** [p32929/EasiestSqlLibrary#4]
thank for this library..
please add a code about

-reading db from local folder / assets
-location where we can find the db.
-how to save the entire database to local folder

thank you

**Comment by p32929** [comment]
Sure. I'll do that. Thanks for your feedback.

**Comment by ghaizar** [comment]
Cursor cursor = easiestDB.searchValuesInMultipleColumns(1,
        new Datum(1, "Value1"),
        new Datum(2, "Value2")
);
boolean matched = cursor.getCount() > 0;

its say where = ? AND ?

**Comment by p32929** [comment]
to be honest, I'm not really good at SQL. That's the reason why I created this library. So, if there's an error, feel free to explain a little bit. Would be very helpful in improving the library. thanks
