### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by cookieukw** [p32929/EasiestSqlLibrary#5]
There are a few ways to encrypt sqlite data based on a StackOverflow article. could you implement a similar system in this library?

https://stackoverflow.com/questions/29746231/android-encrypt-decrypt-sqlite-database-100-secure

**Comment by p32929** [comment]
That's a good idea. I will take a look at the link soon & hopefully implement them in the library. Thanks :)

**Comment by cookieukw** [comment]
Taking advantage, I would also find interesting a way to export and import the data. It is possible to do this, of course, but it is very tiring to do the same system in multiple applications. it would be nice to add these ways to export the data (not necessarily then). thanks

**Comment by p32929** [comment]
Good ideas. Surely with enough time and code, any feature can be implemented
