### ISSUE TITLE
A possible mistake

### ISSUE THREAD

**Issue by cookieukw** [p32929/EasiestSqlLibrary#6]
I use a recyclerView and add items to it. So far so good (it's a chat), I happen to add this item to sqlite using the library, if I want to remove this item (which in this case would be a message) I can't because I don't have the id of this item (in sqlite ). Now if I exit the app and return, I already have the ids because in the method of getting all the items, I also have all the ids. I think there could be a way to send the item to sqlite and get the id of that item, I don't know if it's possible. As I can't modify the libs (I only have android) so I can only report these bugs instead of forking and fixing

**Comment by p32929** [comment]
So, while getting data from a table, you can specify whether or not if you want to get the id from the table too. refer to the doc for more info: https://github.com/p32929/EasiestSqlLibrary#get-all-data-from-a-table

**Comment by cookieukw** [comment]
Yes, that I already know. what I meant is that if this is realtime there is no way to get the id. for example, add a message to chat and at the same time to sqlite, but the user decides to delete this message. there will be no way to delete from sqlite unless it exits the application and getAllDataFrom(int tableIndex) plus method can be used. One more example, instead of the addDataInTable method returning a Boolean, it returns an int variable equivalent to the id of this item

**Comment by p32929** [comment]
Oww, I see. Thats a very good idea. If you want, you may update the function and the doc and make a pull request. Or if I have to do, I can do it a few days later. Thanks for the tip btw :)

**Comment by cookieukw** [comment]
Okay. I don't deal with projects like this because I use Android so I can only wait. Thanks

**Comment by p32929** [comment]
Oww, in that case, if you don't need the feature, I think, I'd rather wait to see if someone will actually need the feature :)

**Comment by cookieukw** [comment]
I really need this resource, what happens is that I only have one phone and I can't make the modification in the library (in this case, I would have to have a pc)
